# Generated by Django 4.2.5 on 2023-12-08 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='artist',
        ),
        migrations.AlterField(
            model_name='artist',
            name='genre',
            field=models.ManyToManyField(through='searches.ArtistGenre', to='searches.genre'),
        ),
    ]
