# Generated by Django 4.2.5 on 2023-12-08 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0002_remove_genre_artist_alter_artist_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='genre',
            new_name='genres',
        ),
        migrations.AddField(
            model_name='album',
            name='record_labels',
            field=models.ManyToManyField(through='searches.AlbumRecordLabel', to='searches.recordlabel'),
        ),
        migrations.AddField(
            model_name='genre',
            name='artists',
            field=models.ManyToManyField(related_name='art', through='searches.ArtistGenre', to='searches.artist'),
        ),
        migrations.AddField(
            model_name='recordlabel',
            name='albums',
            field=models.ManyToManyField(through='searches.AlbumRecordLabel', to='searches.album'),
        ),
    ]
